# ==============================================================================
# Site Settings
# ==============================================================================
title: Notes by Anuj Mohite
author: Anuj Rajesh Mohite
description: >-
  Software Engineer | Backend | Compilers | Linux
url: "https://notes-by-4c1ae5.gitlab.io"
baseurl: ""

# ==============================================================================
# Social Settings
# ==============================================================================
twitter_username: anujrmohite
github_username: anujrmohite

# ==============================================================================
# Build Settings
# ==============================================================================
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:slug/

# ==============================================================================
# Plugins
# ==============================================================================
plugins:
  - jekyll-feed

# ==============================================================================
# Assets
# ==============================================================================
sass:
  style: compressed

# ==============================================================================
# Excludes
# ==============================================================================
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
