# ==============================================================================
# Site Settings
# ==============================================================================
title: Notes by Your Name
author: Your Name
description: >-
  Your tagline here.
url: "https://notes-by-4c1ae5.gitlab.io"
baseurl: "/notes-by"

# ==============================================================================
# Social Settings
# ==============================================================================
twitter_username: yourusername
github_username: yourusername

# ==============================================================================
# Build Settings
# ==============================================================================
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:slug/

# ==============================================================================
# Plugins
# ==============================================================================
plugins:
  - jekyll-feed

# ==============================================================================
# Assets
# ==============================================================================
sass:
  style: compressed

# ==============================================================================
# Excludes
# ==============================================================================
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
